### ISSUE TITLE
Use DisplayTime when TimeTabledDateTime & ExpectedDateTime null

### ISSUE THREAD

**Issue by svartis** [boghammar/MMM-SL-PublicTransport#24] opened 2018-04-15 20:22 UTC
My station in Midsommarkransen (9264) is returning "TimeTabledDateTime" & "ExpectedDateTime" as null.
This is normal for "Subway before transition: null" according to Trafiklab documentation.

Mayby there should be a setting to use "DisplayTime" as departure time instead (This would have been my preferred choose anyway).
And something that defaults to "DisplayTime" if "TimeTabledDateTime" & "ExpectedDateTime" is null.

**Settings;**
stationid: [9264],   
stationname: ['Midsommarkransen'],      
direction: 1,      

**Example response for this station:**
   {  
            "GroupOfLine":"Tunnelbanans röda linje",
            "DisplayTime":"26 min",
            "TransportMode":"METRO",
            "LineNumber":"14",
            "Destination":"Fruängen",
            "JourneyDirection":2,
            "StopAreaName":"Midsommarkransen",
            "StopAreaNumber":0,
            "StopPointNumber":0,
            "StopPointDesignation":"100",
            "TimeTabledDateTime":null,
            "ExpectedDateTime":null,
            "JourneyNumber":0,
            "Deviations":null
         },

**Comment by boghammar** [comment] 2018-04-16 20:26
Good point, thanks for that 

- I'll make sure to handle null values and fallback on displaytime if not available
- I'll make it an option to always use displaytime if you want to use that instead
- I will maybe implement handling internal updates of displaytime between UI updates if it dont get too messy. If messy it will make it to the next release ;)

The rational for not using displaytime is that I dont want to call the API too often. Instead between UI updates I calculate what should be the expected arrival time. That could be done with displaytime also but its easier to do it with an actual proper ExpectedDateTime property.

I did not get the "Subway before transition: null", what's that? And why would they not send the proper   ExpectedDateTime if they can send displaytime  if they can calculate the displaytime ... strange.

**Comment by svartis** [comment] 2018-04-16 21:30
Ah, now I know what "Subway before transition: null" is. There was some information in the general API description. 

-----------------------------------

Some changes were made in response to the structure to make it more consistent between metro departures and other modes of transport, and that it has begun retrieving all Metro information from the same source as other modes of transport departures. This means that you will be able to get as much information about a metro resignation as the other.

**The transition to the new traffic source for Metro departures take place in several stages. The green and blue metro lines have gone over to retrieve data in the same way as for other modes of transport. Red line remains and there is still no complete schedule for when the transition takes place, but in the current situation is a reasonable guess that it may take place during 2017.**

The following documentation will response elements that apply to subway before the transition to the new information recorded with Metro before the transition .

**Comment by boghammar** [comment] 2018-04-17 18:58
Ok, I have updated the code. Please try now without changing the configuration. If you want to force DisplayTime as the preferred way of displaying departure times add the useDisplayTime set to true in the configuration.

I have updated the readme with a section on DisplayTime, read that and feedback please.

Closing this now, if you see any issues please feel free to submit another issue.

**Closed by boghammar** 2018-04-17 18:58 UTC
Labels: bug

**Comment by svartis** [comment] 2018-04-20 10:46
I have tested now and it is working as expected with the default value and setting it to true.
The readme looks good to. I can understand the diffrent cases for how this property is used.

And it is a nice touch with the dot '.' in the end if only DisplayTime is avalible from the service.

Great work :)

**Comment by boghammar** [comment] 2018-04-20 12:28
Thanks for the feedback. Great that it works as intended.
